# Site setings
name: 'Boris Paccou - '
description: 'Simple personnal blog - Nothing too fancy'
meta_description: 'Boris Paccou'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://borispaccou.github.io/
disqus: 'borispaccou'
mailchimp_url: ''
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Boris Paccou'
  image: 'author.png'
  greetings: 'Hi there!'
  description: "My name is Boris. I'm a freelance front-end developer, entrepreneur and author based in Lyon, Fr. It’s nice to meet you."
  bio: 'My bio - todo'

# Contact form setings
email: youremail@email.com
contact_page_description: "Texte de contact !"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter:
facebook:
github: 'username'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'username'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
